FILTROS_VISUAL_PATCH = r'''
# =========================================================
# FILTROS OPERACIONAIS — PADRÃO VISUAL GESTÃO DE ENTREGAS
# =========================================================
# Aplicado imediatamente antes do título principal para que as regras
# fiquem depois dos estilos genéricos dos formulários.

_filtros_visual_anchor = 'st.markdown(f\'<h1 class="app-title">{UI_CONFIG["section_main_title"]}</h1>\', unsafe_allow_html=True)\n'
_filtros_final_css = '<style>div[data-testid="stForm"]{background:#f8fafc!important;border:1px solid #cbd5e1!important;border-radius:8px!important;padding:12px!important;box-shadow:none!important;margin-bottom:.65rem!important}div[data-testid="stForm"] label,div[data-testid="stForm"] [data-testid="stWidgetLabel"] p{color:#1f2937!important;font-size:.82rem!important;font-weight:500!important}div[data-testid="stForm"] div[data-baseweb="select"]>div{background:#f1f3f6!important;border-color:transparent!important;border-radius:6px!important;min-height:36px!important;box-shadow:none!important}div[data-testid="stForm"] div[data-baseweb="input"]{background:#f1f3f6!important;border-color:transparent!important;border-radius:6px!important;min-height:36px!important;box-shadow:none!important}div[data-testid="stForm"] div[data-baseweb="input"] input{background:transparent!important;color:#20252b!important}div[data-testid="stForm"] input::placeholder{color:#8a94a3!important;opacity:1!important}div[data-testid="stForm"] div[data-baseweb="select"]>div:focus-within,div[data-testid="stForm"] div[data-baseweb="input"]:focus-within{border:1px solid #aab2bd!important;box-shadow:none!important}div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-primaryFormSubmit"],div[data-testid="stFormSubmitButton"] button[kind="primary"]{background:#111!important;border:1px solid #111!important;color:#fff!important;border-radius:6px!important;min-height:34px!important;font-weight:650!important;box-shadow:none!important}div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-primaryFormSubmit"]:hover,div[data-testid="stFormSubmitButton"] button[kind="primary"]:hover{background:#222!important;border-color:#222!important;color:#fff!important}div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-secondaryFormSubmit"],div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-secondary"],div[data-testid="stFormSubmitButton"] button[kind="secondary"]{background:#fff!important;border:1px solid #cbd5e1!important;color:#5b6470!important;border-radius:6px!important;min-height:34px!important;font-weight:500!important;box-shadow:none!important}div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-secondaryFormSubmit"]:hover,div[data-testid="stFormSubmitButton"] button[data-testid="stBaseButton-secondary"]:hover,div[data-testid="stFormSubmitButton"] button[kind="secondary"]:hover{background:#f5f6f8!important;border-color:#aeb6c2!important;color:#222!important}div[data-testid="stForm"] [data-testid="stVerticalBlock"]{gap:.65rem!important}</style>'
_filtros_visual_injection = 'st.markdown(' + repr(_filtros_final_css) + ', unsafe_allow_html=True)\n' + _filtros_visual_anchor
if _filtros_visual_anchor not in _source:
    raise RuntimeError("Ponto do título principal não encontrado para aplicar o padrão visual dos filtros.")
_source = _source.replace(_filtros_visual_anchor, _filtros_visual_injection, 1)
'''
